language: java
jdk: 
  - oraclejdk8
  
branches:
only:
    - master

script:
    # SONAR
    - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=delgadotrueba-github -Dsonar.login=$SONAR_TOKEN
    
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_ApiKey
  app: api-rest-with-spring
  on:
    branch: master